language: c
sudo: required

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - tree
      - tshark

script:
  - ./autogen.sh
  - ./configure --prefix=/tmp/sysklogd
  - make clean
  - make -j5
  - sudo make check || (cat test/test-suite.log; false)
  - make install-strip
  - tree /tmp/sysklogd
