name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./autogen.sh && ./configure
    - name: build
      run: make
    - name: clang-tidy check
      uses: muxee/clang-tidy-action@0.0.1-rc1
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
